version: "3.6"
services:

  postgres:
    image: postgres:12-alpine
    restart: unless-stopped
    container_name: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      - POSTGRES_USER=fabio
      - POSTGRES_PASSWORD=fabio
      - POSTGRES_DB=prod
    volumes:
      - ./postgres/db:/docker-entrypoint-initdb.d/
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  service-api:
    image: service-api
    build:
      context: ./service-api
    container_name: service-pai
    ports:
      - 8080:8080

  service-principal:
    image: service-principal
    build:
      context: ./service-principal
    container_name: service-principal
    ports:
      - 8082:8082
    depends_on:
      - service-api
      - kafka
  service-retry:
    image: service-retry
    build:
      context: ./service-retry
    container_name: service-retry
    ports:
      - 8081:8081
    depends_on:
      - service-api
      - kafka